### ISSUE TITLE
the video "Step 4 - Piano Action Frame" is private. Could you give a new link? 

### ISSUE THREAD

**Issue by BetsyTsng** [gzweigle/DIY-Grand-Digital-Piano#20]
the video "Step 4 - Piano Action Frame" is private. Could you give a new link?

**Comment by BetsyTsng** [comment]
i really need this video to learn how to make frame of the action.

**Comment by davidedelvento** [comment]
https://pianoclack.com/forum/d/170-build-your-own-hybrid-piano-step-two-the-cabinet/7

**Comment by BetsyTsng** [comment]
sorry, i read carefully this repo, and found that this video just not be done.

**Comment by gzweigle** [comment]
Thanks, yes it is not done.

**Comment by gzweigle** [comment]
I changed the video to public and also made a video documenting issues with it.
