### ISSUE TITLE
HW: crosstalk

### ISSUE THREAD

**Issue by gzweigle** [gzweigle/DIY-Grand-Digital-Piano#27]
In working on note-to-note consistency, I notice a slight cross-talk between channels (notes).
Need to track this down.

**Comment by davidedelvento** [comment]
I suspect optical crosstalk from the sensors themselves. I noticed this in my preliminary testing and it is one of the reasons I settled on the QRE1113 rather than the CNY70

**Comment by gzweigle** [comment]
Interesting.  I will investigate. Am thinking (hoping) that it is an issue with my test setup, not the circuits.

I am taking very precise test position measurements so seeing interesting phenomena. For example, measurements influenced by leaning against piano slightly during test!

**Comment by gzweigle** [comment]
test setup
