### ISSUE TITLE
HW: missing kicad file for the ACE board

### ISSUE THREAD

**Issue by davidedelvento** [gzweigle/DIY-Grand-Digital-Piano#68]
Ditto

**Comment by gzweigle** [comment]
Added.

**Comment by davidedelvento** [comment]
Is it intentional that these are for kicad v8 whereas everything else is for kicad v7? The incompatibility between different versions of kicad is frustrating...

**Comment by gzweigle** [comment]
Agree. I've been thinking about adding v8 version to repo for all boards. Your comment motivated me to give it a try.
