### ISSUE TITLE
HW: Pedal resistors

### ISSUE THREAD

**Issue by davidedelvento** [gzweigle/DIY-Grand-Digital-Piano#76]
This is probably leftover from #54 -- the BOM states 10 Ohm for R22 R26 and R29. But KiCad still has 10 kOhm. I am proceeding assuming that the BOM is correct, but please confirm.

**Comment by gzweigle** [comment]
Correct 10 ohms.

**Comment by davidedelvento** [comment]
Awesome, thanks. Not closing this issue since you may want to fix the value in KiCad.

**Comment by gzweigle** [comment]
Documentation - use bom not schematic so we're good.
