### ISSUE TITLE
Number of SCA cards

### ISSUE THREAD

**Issue by davidedelvento** [gzweigle/DIY-Grand-Digital-Piano#8]
If my understanding is correct, one needs 16 SCA cards for the hammers and 16 for the dampers. Is that correct?
If so, write it in the paragraph https://github.com/gzweigle/DIY-Grand-Digital-Piano/tree/main/packages/StemPianoG#six-channel-analog-pcb-link

**Comment by gzweigle** [comment]
Just one is needed. I clarified in documentation per suggestion. Thanks!
