### ISSUE TITLE
DOC: power jumper

### ISSUE THREAD

**Issue by davidedelvento** [gzweigle/DIY-Grand-Digital-Piano#88]
In your latest video you mention very quickly the "power jumper" and repeatedly say "see links below for more info". Below there are only link to the github repos. The power jumper is not mentioned anywhere in text that github can find. The only reference I could find is in the picture of the page https://github.com/stem-piano/stem-piano-g-main/blob/cadb8c2ac602357a89b7d46fda0e3810b8dbe8d5/documentation/users_manual.md -- but as far as I can tell it has been removed on more recent version of that picture.

Worth adding that info to the text of the page https://github.com/stem-piano/stem-piano-g-main/blob/cadb8c2ac602357a89b7d46fda0e3810b8dbe8d5/documentation/construction_subsections/subsection3a_circuit_board_assembly.md in my opinion.

I thought that there was another thing missing, but I cannot rewatch the video now and I don't recall, so if you have time maybe a quick check if everything you wrote in all the boxes you included in the video can be actually be found on the docs.

UPDATE: that picture is still used in the most recent version of the documentation at https://github.com/stem-piano/stem-piano-g-main/blob/main/documentation/users_manual.md#quick-start-guide-without-damper-board but my point remains that it's a hard to find and not descriptive about what is needed (okay, as little as "purchase such and such jumper and place it there", but still...)

**Comment by gzweigle** [comment]
Sure enough, the documentation is missing.
Added with commits "issue 88 - power jumper".

Also noting that this issue is number is also the number of keys on a piano!
