### ISSUE TITLE
HW: Label the LEDs

### ISSUE THREAD

**Issue by davidedelvento** [gzweigle/DIY-Grand-Digital-Piano#95]
Add to the silkscreen of the IPS some short abbreviation of the meaning of the LEDs, per the description at https://github.com/stem-piano/stem-piano-g-main/blob/main/documentation/users_manual.md#front-leds--test-points

For example: proc, damp, strike, pedal

**Comment by gzweigle** [comment]
I added a comment in the users manual that LED functionality is set by the firmware.

I'd prefer not to put any labels on the hardware that make assumptions about the firmware. However, I will add an item to IPS 2.1 issue to try and make space on PCB for someone to put stickers next to LED.
