### ISSUE TITLE
FW: simplify Ethernet activation

### ISSUE THREAD

**Issue by davidedelvento** [gzweigle/DIY-Grand-Digital-Piano#97]
According to https://github.com/stem-piano/stem-piano-g-main/blob/main/documentation/users_manual.md#ethernet ethernet data is sent when a key is held and pedal depressed. I see two problems with this approach:

* Can (and will!) be triggered involuntarily when playing. Probably not a bit deal, but still cycles wasted if unintended
* Hard to trigger during testing when pedal may not be available

I recommend switching to a procedure that uses ETHERNET_SEND_KEY as it is done for the damper board

**Comment by gzweigle** [comment]
The software now sends all 96 analog inputs all the time.

I made a YouTube video showing the new functionality -

https://www.youtube.com/watch?v=AWMlzoCq9G0
